# Generated by Django 5.2.5 on 2025-10-14 23:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('IdComprobante', models.AutoField(primary_key=True, serialize=False)),
                ('Receta', models.CharField(default='Receta genérica', max_length=100)),
                ('Costo_Total', models.IntegerField(default=0)),
                ('Factor_Multiplicacion', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('Iva', models.DecimalField(decimal_places=4, default=0.19, max_digits=10)),
                ('Precio_Bruto', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Comprobante',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Entrega', models.DateTimeField(blank=True, null=True)),
                ('Fecha_Modificacion', models.DateTimeField(auto_now=True)),
                ('Usuario', models.CharField(default='Usuario genérico', max_length=100)),
                ('Receta', models.CharField(default='Receta genérica', max_length=100)),
                ('Cambio_Realizado', models.TextField(blank=True, default='Sin cambios', null=True)),
            ],
            options={
                'db_table': 'Historial',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('idIngrediente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Ingrediente', models.CharField(default='Ingrediente genérico', max_length=100)),
                ('Calidad', models.CharField(default='Normal', max_length=45)),
                ('Costo_Unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('UnidadMedicion_idUnidadMedicion', models.CharField(default='Unidad', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Receta', models.CharField(default='Receta genérica', max_length=100)),
                ('Categoria', models.CharField(default='Sin categoría', max_length=45)),
                ('Aporte_Calorico', models.IntegerField(default=0)),
                ('Tiempo_Preparacion', models.CharField(default='0 min', max_length=45)),
                ('Procedimiento', models.TextField(default='Sin procedimiento')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('idRecetaIngrediente', models.AutoField(primary_key=True, serialize=False)),
                ('Receta_idReceta', models.CharField(default='Receta genérica', max_length=100)),
                ('Ingrediente_idIngrediente', models.CharField(default='Ingrediente genérico', max_length=100)),
                ('Cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreRol', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedicion',
            fields=[
                ('idUnidadMedicion', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Unidad', models.CharField(default='Sin unidad', max_length=100)),
                ('Abreviatura', models.CharField(default='NA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(blank=True, db_column='Rol', default='Sin rol', max_length=45, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
