# Generated by Django 5.2.5 on 2025-10-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='Costo_Total',
            field=models.IntegerField(db_column='Costo_Total', default=0),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='Factor_Multiplicacion',
            field=models.DecimalField(db_column='Factor_Multiplicacion', decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='IdComprobante',
            field=models.AutoField(db_column='IdComprobante', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='Iva',
            field=models.DecimalField(db_column='Iva', decimal_places=4, default=0.19, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='Precio_Bruto',
            field=models.IntegerField(db_column='Precio_Bruto', default=0),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='Receta',
            field=models.CharField(db_column='Receta', default='Receta genérica', max_length=100),
        ),
        migrations.AlterField(
            model_name='historial',
            name='Cambio_Realizado',
            field=models.TextField(blank=True, db_column='Cambio_Realizado', default='Sin cambios', null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='Fecha_Entrega',
            field=models.DateTimeField(blank=True, db_column='Fecha_Entrega', null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='Fecha_Modificacion',
            field=models.DateTimeField(auto_now=True, db_column='Fecha_Modificacion'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='Receta',
            field=models.CharField(db_column='Receta', default='Receta genérica', max_length=100),
        ),
        migrations.AlterField(
            model_name='historial',
            name='Usuario',
            field=models.CharField(db_column='Usuario', default='Usuario genérico', max_length=100),
        ),
        migrations.AlterField(
            model_name='historial',
            name='idHistorial',
            field=models.AutoField(db_column='idHistorial', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='Calidad',
            field=models.CharField(db_column='Calidad', default='Normal', max_length=45),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='Costo_Unitario',
            field=models.DecimalField(db_column='Costo_Unitario', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='Nombre_Ingrediente',
            field=models.CharField(db_column='Nombre_Ingrediente', default='Ingrediente genérico', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='UnidadMedicion_idUnidadMedicion',
            field=models.CharField(db_column='UnidadMedicion_idUnidadMedicion', default='Unidad', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='idIngrediente',
            field=models.AutoField(db_column='idIngrediente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Aporte_Calorico',
            field=models.IntegerField(db_column='Aporte_Calorico', default=0),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Categoria',
            field=models.CharField(db_column='Categoria', default='Sin categoría', max_length=45),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Imagen',
            field=models.ImageField(blank=True, db_column='Imagen', null=True, upload_to='recetas/'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Nombre_Receta',
            field=models.CharField(db_column='Nombre_Receta', default='Receta genérica', max_length=100),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Procedimiento',
            field=models.TextField(db_column='Procedimiento', default='Sin procedimiento'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='Tiempo_Preparacion',
            field=models.CharField(db_column='Tiempo_Preparacion', default='0 min', max_length=45),
        ),
        migrations.AlterField(
            model_name='receta',
            name='idReceta',
            field=models.AutoField(db_column='idReceta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='Cantidad',
            field=models.DecimalField(db_column='Cantidad', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='Ingrediente_idIngrediente',
            field=models.CharField(db_column='Ingrediente_idIngrediente', default='Ingrediente genérico', max_length=100),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='Receta_idReceta',
            field=models.CharField(db_column='Receta_idReceta', default='Receta genérica', max_length=100),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='idRecetaIngrediente',
            field=models.AutoField(db_column='idRecetaIngrediente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidadmedicion',
            name='Abreviatura',
            field=models.CharField(db_column='Abreviatura', default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='unidadmedicion',
            name='Nombre_Unidad',
            field=models.CharField(db_column='Nombre_Unidad', default='Sin unidad', max_length=100),
        ),
        migrations.AlterField(
            model_name='unidadmedicion',
            name='idUnidadMedicion',
            field=models.AutoField(db_column='idUnidadMedicion', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='ingrediente',
            table='Ingrediente',
        ),
        migrations.AlterModelTable(
            name='receta',
            table='Receta',
        ),
        migrations.AlterModelTable(
            name='recetaingrediente',
            table='RecetaIngrediente',
        ),
        migrations.AlterModelTable(
            name='unidadmedicion',
            table='UnidadMedicion',
        ),
    ]
